### ISSUE TITLE
Local development and debugging support

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-server#242]
In an older version of azure-mobile-apps-net-server I managed to get the local development and debugging working, the steps I used back then were roughly similar to the wiki that explains how to set this up in the latest version: https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend

But with this current version of azure-mobile-apps-net-server it is not working. The call to LoginAsync(MobileServiceAuthenticationProvider provider, JObject token) on the client completes successfully (I'm using the latest stable releases of azure-mobile-apps-net-client and azure-mobile-apps-net-server) and I get a valid MobileServiceUser back (the UserId and the MobileServiceAuthenticationToken within the MobileServiceUser are both properly filled). However when I then call an API controller on the backend using InvokeApiAsync(string apiName, HttpMethod method, IDictionary<string, string> parameters, CancellationToken cancellationToken = default(CancellationToken)) from the client where the server controller has the [Aurhorize] attribute is set on the class (or the method), it returns a "not authorized" error. I have loaded the relevant symbol sources and found that the place where it goes wrong is here:
`  protected virtual bool IsAuthorized(HttpActionContext actionContext)
        {
            if (actionContext == null)
            {
                throw Error.ArgumentNull("actionContext");
            }

            IPrincipal user = actionContext.ControllerContext.RequestContext.Principal;
            if (user == null || user.Identity == null || !user.Identity.IsAuthenticated)
            {
                return false;
            }
`
That code is from here: >	Microsoft.Owin.Security.dll!Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware<Microsoft.Azure.Mobile.Server.Authentication.AppServiceAuthenticationOptions>.Invoke(Microsoft.Owin.IOwinContext context) Line 30

The problem is that user.Identity is null at this point (despite the fact that the LoginAsync on the client went through successfully earlier without any errors) and then the above IsAuthorized method returns false, meaning "not authorized". That is then passed back to the client app and the API call then fails.

This is really holding us back and taking up a lot of my time. We need to be able to run azure-mobile-apps-net-server locally while we are developing our app.

**Comment by fileman** [comment]
Are you using IIS or IISExpress? I've solved with first

**Comment by ltaljaard** [comment]
I started with IIS Express and then swithed to IIS, same issue persists with IIS.

**Comment by ltaljaard** [comment]
Ok Microsoft, I've gone through hell trying to figure this out over the past two weeks and just returned from there to tell you all about it. Below is how to reproduce the problem so that you can fix it and bring your documentation and Quickstart solutions back into the 21st century.

My mortal sin was trying to update the backend solution to run the latest ".NET Framework 4.7.1". I'm referring to the "Runtime" solution as you call it in the Quickstart Xamarin.Forms project/solution that one can downloaded from the Azure Portal under your Mobile App.

I managed to "upgrade" the front-end Xamarin.Forms solution from the PCL based solution that one gets when you download the Quickstart solution to the latest .NET Standard 2.0 based solution. Actually I ended up creating a new .NET Standard Xamarin.Forms solution from Visual Studio 2017 and ported the relevant Azure Mobile App code into it. The point is that the front-end solution works fine whether it's a PCL or a .NET Standard 2.0 based solution, which is a good thing. That said, you should update your Quickstart solution and documentation to be based on a .NET Standard 2.0 solution because PCL's are no longer supported properly, e.g. it's not even possible to create a new PCL based solution from Visual Studio 2017 anymore. But this is just an aside. The rest of this post focuses on the backend solution as that is where the technical problem lies.

The Quickstart TodoList "runtime" Quickstart project comes out as targeting the .NET Framework 4.6.

Step 1: Add rudimental support for Authentication to the backend and front-end solutions: In the backend solution, add an TestAuthenticationController with the [Authorize] and [MobileAppController] attributes, and a public Get() method and put a breakpoint inside the Get method to confirm whether or not it gets hit during local debugging/execution later on. In the front-end solution, add a call to LoginAsync() as decribed in posts like these:
* Some of this: [https://docs.microsoft.com/en-gb/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users](https://docs.microsoft.com/en-gb/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users)
* Some of this: [https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend)
So add code to log in (server-side flow) and then call (or try to call) the backend "TestAuthentication" API.

Step 2: It is fine to go to the Properties of the TodoListService in Visual Studio at this point already and change the Target Framework to 4.7.1. Do that now. Also Publish your bakcend app to Azure. Once you've done that and then rigt-click the Solution node and select Restore NuGet packages everything still works fine: the authentication works whether you run your front-end app in Debug mode from Visual Studio 2017 (where #DEBUG will be set and where the locally running solution will then be used as the back-end) or in Release mode (where #DEBUG will not be set and therefore where the backend solution will be running in the cloud on Azure). Test this at this point to prove to yourself that both modes (local and remote execution) still work fine at this point, I.e. the front-end app should pass the Authentication and be able to call the "TestAuthentication" API, whether the backend is running locally or on Azure.

Step 3: Take a backup of your packages.config file in the backend solution, which should look something like this at this point:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoMapper" version="5.2.0" targetFramework="net471" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.OData" version="5.7.0" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Tracing" version="5.2.3" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Authentication" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Entity" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Home" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Quickstart" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Tables" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Data.Edm" version="5.8.1" targetFramework="net471" />
  <package id="Microsoft.Data.OData" version="5.8.1" targetFramework="net471" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net471" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net471" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.3.308261200" targetFramework="net471" />
  <package id="System.Spatial" version="5.8.1" targetFramework="net471" />
</packages>`

Step 4: From Package Manager Console, run "Update-Package" to properly replace all the .NET Framework packages with the 4.7.1 equivalents. I have noted there is some link between the .NET Framework 4.7.1 and the NuGet package Microsoft.AspNet.WebApi.Core (latest version is 5.2.4 as can be seen on nuget.org) and the assembly references for System.Web.Http and System.Net.Http.Formatting. The Update-Package causes version 5.2.4 to be used and referenced for System.Web.Http and System.Net.Http.Formatting in the Web.config file. The original TodoList "runtime" Quickstart backend solution uses version 5.2.3 of System.Web.Http and System.Net.Http.Formatting (which is tied to version 5.2.3 of Microsoft.AspNet.WebApi.Core). However the Update-Package that you just ran has replaced the 5.2.3's (which go with the .NET Framework 4.6) with the newer 5.2.4's (which go with the .NET Framework 4.7). Perhaps the problem is not caused by System.Web.Http and System.Net.Http.Formatting themselves but by one of the others listed in the above <packages> list from step 3 - but it is definitely caused by one of these packages (this is proved by step 4 below: the problem is reversible by only changing the package versions). Once you have done this, the following happens: The authentication DOES NOT WORK when you run your front-end app in DEBUG mode (where #DEBUG will be set and where the local solution will be used as the back-end), however it DOES WORK in Release mode (where #DEBUG will not be set and therefore where the backend solution will be running in the cloud on Azure). Here is how your packages.config will look at this point, i.e. with the newer packages that come with .NET Framework 4.7.1, where the authentication does NOT work while running/debugging the solution locally:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoMapper" version="6.2.2" targetFramework="net471" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.4" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.4" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.OData" version="5.7.0" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.4" targetFramework="net471" />
  <package id="Microsoft.AspNet.WebApi.Tracing" version="5.2.4" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Authentication" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Entity" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Home" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Quickstart" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Azure.Mobile.Server.Tables" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.Data.Edm" version="5.8.3" targetFramework="net471" />
  <package id="Microsoft.Data.OData" version="5.8.3" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Logging" version="5.2.1" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.2.1" targetFramework="net471" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net471" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net471" />
  <package id="Microsoft.Owin.Security" version="4.0.0" targetFramework="net471" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="11.0.1" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net471" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.2.1" targetFramework="net471" />
  <package id="System.Spatial" version="5.8.3" targetFramework="net471" />
</packages>`

Step 4: To prove that the problem is reversible by changing only the package versions: You can get the authentication to work again for both the local execution/debugging and the server-side execution by doing this: in your Web.Config file, delete all the <dependentAssembly> sections within the <assemblyBinding> section. Then overwrite the contents within your packages.config file with your backed up contents from step 3. Then, from Package Manager Console, run this: "Update-Package -reinstall". That restores the older packages that you just specified by manually reverting to the earlier version of your packages.config file, and it also re-generates the correctly versioned <dependentAssembly> entries into your Web.config file. Now publish your updated backend app to Azure. Once you have done this you can restart the backend app both locally and on Azure, and the authentication will work in both cases.

The above steps prove the following:
1. That the authentication anomaly with local debugging/execution is directly related to attempting to use a later .NET Framework version than 4.6 for the backend app.
2. Specifically, that one or more of the package versions listed in step 3 above (from packages.config) are causing the local authentication debugging/execution anomaly.

Please keep this ticket open until all of the following have been addressed:
A) Update front-end Quickstart solution to be .NET Standard 2.0 based instead of PCL based.
B) Update back-end Quickstart solution to be compatible with .NET Framework 4.7.1 (and hopefully upwards as well).
C) Update the documentation accordingly. This should include the URL's listed above in Step 1.

**Comment by ltaljaard** [comment]
Ok, I went through the list of packages one by one to determine which one(s) cause this problem. It turns out that all of them are fine apart from package System.IdentityModel.Tokens.Jwt . As soon as you update that one to the latest version the local debugging stops working when you call an API with an [Authenticated] attribute. The same steps as above still apply but here is a bit of a shortcut to allow you to flip between a working backend solution where the authentication works and a broken backend solution where the authentication fails:

1. Take the Quickstart backend solution from the Azure Portal and add rudimentary authentication (already eplained better in previous post).

2. Right-click the TodoListService project node in Solution Explorer and select Properties and change the Target framework from 4.6 to 4.7.1 (on the Application tab of the Properties window). right-click on the top Solution node in Solution Explorer and select "Restore Nuget Packages". Clean and rebuild the solution.

3. Publish the project to Azure. Run it both locally and from Azure to confirm that the API call to the authenticated API still works fine at this point for both cases.

4. Take a backup of your package.config file so you can compare it to the soon-to-be-updated one. Notice the version of package System.IdentityModel.Tokens.Jwt is still "4.0.3.308261200".

5. In the Web.Config file, delete all the <dependentAssembly> sections.

6. From Package Manager Console, run "Update-Package". This bumps everything up to the latest package versions. The version of the problematic package System.IdentityModel.Tokens.Jwt will now be "5.2.1".

7. Clean and rebuild the solution. Publish the project to Azure. Run it both locally and from Azure to confirm that the API call to the authenticated API now still works fine when running on Azure but it FAILS with an "unauthorised" return code/exception when running from your local PC.

8. To un-break it: Delete all the <dependentAssembly> sections from Web.Config, then edit packages.config and manually change the version of the System.IdentityModel.Tokens.Jwt package from "5.2.1" back to "4.0.3.308261200". From Package Manager Console, run "Update-Package -reinstall" (this only reinstalls the versions of the packages as listed in packages.config which is what we want at this point). Clean and rebuild the project. Publish to Azure. Run it both locally and from Azure to confirm that the API call to the authenticated API YET AGAIN works fine at this point for both cases.

9. To break it again, flip the version of package System.IdentityModel.Tokens.Jwt back to "5.2.1", delete the <dependentAssembly> sections from Web.Config, run "Update-Package -reinstall", clean & rebuild, publish to Azure and run again locally and note the authentication during local execution is broken again.

10. Repeat steps 8 & 9 until you have convinced yourself that the version of package System.IdentityModel.Tokens.Jwt is the ONLY thing that breaks the authentication during the local execution of the backend solution.

Ok Microsoft, hopefully you can pick it up from here and fix the underlying problem? I'm sure it's not going to be 100 years before more people start updating their backend packages and they will then all run into this most infuriating and seemingly inexplicable problem!

**Comment by codegrue** [comment]
I think you are assuming they are actually maintaining and updating this library. They already started they are working on its replacement instead.
________________________________

**Comment by ltaljaard** [comment]
A replacement will take years, this must be maintained and supported until then.

Kind regards,
Louis

On 22 Mar 2018, at 14:04, codegrue <notifications@github.com> wrote:

I think you are assuming they are actually maintaining and updating this library. They already started they are working on its replacement instead.
________________________________

**Comment by dgerding** [comment]
@codegrue Can you point me to the place where they said they are working on a new release?  I've been in touch with some related folks at MS and they never mentioned it. Signals might be crossed somewhere.

**Comment by codegrue** [comment]
This thread:

https://github.com/Azure/azure-mobile-apps-net-server/issues/227

**Comment by dgerding** [comment]
@Italjaard - Do you think there's a possibility of updating the Mobile Apps stack "ourselves"?

**Comment by codegrue** [comment]
I think MS should have at least some resources converting it to dotnetcore and especially odata which has been being converted for about 2 years now.

If not, they should allow public contributors.

**Comment by codegrue** [comment]
@dgerding They have said the roadblock is the port of OData to core, which EF needs to function in a port of Azure Mobile. So that's the component that needs the conversion.

**Comment by ltaljaard** [comment]
@dgerding It sounds promising but I just don't have the time at the moment. For now I have what I need because was (finally) able to convert the client solution to .NET Standard 2.0 and my backend is now running .NET Framework 4.7.1, which meets my needs. I'd be happy to run with this until they release their shiny new planned replacement. Well apart from the login bit which is not great. At the moment I'm using the server-side authentication flow which means users get that ugly browser based login with the Facebook auth provider etc. I guess I should look into the client-side auth flows to get the better UI experience, I guess it's doable with a bit of effort. But please share what you're up to, I'd be interested to see where it leads.

**Comment by elamalani** [comment]
@ltaljaard Thanks for sharing your feedback with detailed steps. I'll review this with the team and keep you posted on the next steps from our end. But as @dgerding suggested, please feel free to fork the repo, make changes to it, and submit a PR. We are very open to community contributions and would appreciate if you are open to sharing.

Thanks!

**Comment by ltaljaard** [comment]
@elamalani Hello, could you give me an update with regards to this compatibility issue between the System.IdentityModel.Tokens.Jwt package version "5.2.1" (its latest version is now "5.2.2") with the latest available azure-mobile-apps-net-server ? I have just updated all my packages and the problem with the local debugging that is described in this issue #242 is still very much there. I have had to manually bump my version of System.IdentityModel.Tokens.Jwt down to "4.0.3.308261200" yet again today before I could get past the "Unauthorized" exception when I call a server-side API with the [Authenticated] attribute set, while running my backend from my local PC.

**Comment by MatkovIvan** [comment]
Hi @ltaljaard 

https://github.com/Azure/azure-mobile-apps-net-server/issues/185#issuecomment-281854496 - this is an explanation and https://github.com/Azure/azure-mobile-apps-net-server/issues/210 is why it is still the case.
